name: CI/CD Workflow

on:
  push:
    branches:
      - main
env:
  NODE_ENV: development
  
jobs:
  build:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test
